### ISSUE TITLE
实现 SpringBoot 自动配置

### ISSUE THREAD

**Issue by yiding-he** [yiding-he/simple-cache#5]
配置项示例：

- `simple-cache.ehcache` : Map<String, EhcacheConfiguration>

```
simple-cache:
  ehcache:
    default-cache:
      max-size: 10000
      time-to-live-seconds: 60
      time-to-idle-seconds: 30
```
